### ISSUE TITLE
Cutlass-test goes into deadlock

### ISSUE THREAD

**Issue by clevercool** [gpgpu-sim/cutlass-gpgpu-sim#2] opened 2018-12-06 07:49 UTC
Hello, 
I have built the executable file 'cutlass-test', but the program would go into deadlock when I run it.
like this:
```
GPGPU-Sim PTX: cudaLaunch for 0x0x40febc (mode=performance simulation) on stream 0
GPGPU-Sim PTX: pushing kernel '_ZN7cutlass4gemm11gemm_kernelINS0_4GemmINS0_14WmmaGemmTraitsILNS_12MatrixLayout4KindE1ELS5_0ENS_5ShapeILi32ELi16ELi16ELi1EEEfNS0_13LinearScalingIfNS0_19FragmentMultiplyAddIfEEEEfS7_NS6_ILi16ELi16ELi16ELi1EEELi8ELi8EiNS0_20WmmaGemmTraitsHelperILS5_1ELS5_0ES7_ffSB_S7_SC_Li8ELi8EiEEEEEEEEvNT_6ParamsE' to stream 0, gridDim= (1,1,1) blockDim = (32,1,1)
GPGPU-Sim uArch: Shader 0 bind to kernel 1 '_ZN7cutlass4gemm11gemm_kernelINS0_4GemmINS0_14WmmaGemmTraitsILNS_12MatrixLayout4KindE1ELS5_0ENS_5ShapeILi32ELi16ELi16ELi1EEEfNS0_13LinearScalingIfNS0_19FragmentMultiplyAddIfEEEEfS7_NS6_ILi16ELi16ELi16ELi1EEELi8ELi8EiNS0_20WmmaGemmTraitsHelperILS5_1ELS5_0ES7_ffSB_S7_SC_Li8ELi8EiEEEEEEEEvNT_6ParamsE'

GPGPU-Sim uArch: CTA/core = 25, limited by: regs
GPGPU-Sim: Reconfigure L1 cache in Volta Archi to 120KB

GPGPU-Sim uArch: ERROR ** deadlock detected: last writeback core 2064 @ gpu_sim_cycle 1568 (+ gpu_tot_sim_cycle 4294917296) (48432 cycles ago)

GPGPU-Sim uArch: DEADLOCK  shader cores no longer committing instructions [core(# threads)]:
GPGPU-Sim uArch: DEADLOCK  0(32) 1(0)> Re-run the simulator in gdb and use debug routines in .gdbinit to debug this
Aborted (core dumped)
```
My cuda version is 9.1:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```
The gpgpu-sim 4.0 have installed successfully.
```
GPGPU-Sim version 4.0.0 (build gpgpu-sim_git-commit-d26501be3e3e8a6fe52409dd7cbaa7fa33e34d5e-modified_0.0) configured with GPUWattch.

----------------------------------------------------------------------------
INFO - If you only care about PTX execution, ignore this message. GPGPU-Sim supports PTX execution in modern CUDA.
If you want to run PTXPLUS (sm_1x SASS) with a modern card configuration, the apps and simulator must be compiled with CUDA 4.2.
You can still run a PASCAL configuration when compiling with 4.2 by setting the $PTXAS_CUDA_INSTALL_PATH directory environment variable.
The following text describes why:
If you are using PTXPLUS, only sm_1x is supported and it requires that the app and simulator binaries are compiled in CUDA 4.2 or less.
The simulator requires it since CUDA headers desribe struct sizes in the exec which change from gen to gen.
The apps require 4.2 because new versions of CUDA tools have dropped parsing support for generating sm_1x
When running using modern config (i.e. pascal) and PTXPLUS with CUDA 4.2, the $PTXAS_CUDA_INSTALL_PATH env variable is required to get proper register usage
(and hence occupancy) using a version of CUDA that knows the register usage on the real card.

----------------------------------------------------------------------------
setup_environment succeeded
```
And I also copy configs in the path.

I have seen The deadlock situation in gpgpu-sim 3.0 in my program with bugs. And I notice the gpgpu-sim updates frequently in recent one month. I doubt whether it is related to the gpgpu-sim version.

Could you tell me more detail about the configuration about this program. like, the gpgpu-sim Commits ID you based on or other information. 

Thanks !!!

**Comment by AamirRaihan** [comment] 2019-02-21 08:14
The issue is resolved in the dev branch.

**Comment by aamodt** [comment] 2019-02-21 16:50
closing

**Closed as completed by aamodt** 2019-02-21 16:50 UTC
